@echo off
echo Starting the process...
echo Cleaning up old files that might ruin the process...
call cd output
call "cleanup.bat"
call cd ..
echo Cleaning up done...
echo Creating the circom file...
call dotnet run
call cd output
echo Generating new files...
call circom Converter.circom --r1cs --wasm --sym --c
call node Converter_js/generate_witness.js Converter_js/Converter.wasm input.json witness.wtns
echo New files are ready...
echo Setting up snarkjs...
call snarkjs powersoftau new bn128 12 pot12_0000.ptau -v
( echo Smuky ) ^| snarkjs powersoftau contribute pot12_0000.ptau pot12_0001.ptau --name="Smuky" -v
call snarkjs powersoftau prepare phase2 pot12_0001.ptau pot12_final.ptau -v
call snarkjs groth16 setup Converter.r1cs pot12_final.ptau Converter_0000.zkey
echo Zkey files are ready...
echo Generating proof...
( echo Smuky ) ^| snarkjs zkey contribute Converter_0000.zkey Converter_0001.zkey --name="Smuky" -v
call snarkjs zkey export verificationkey Converter_0001.zkey verification_key.json
echo Verification key is ready...
call snarkjs groth16 prove Converter_0001.zkey witness.wtns proof.json public.json
echo Verifying proof...
call snarkjs groth16 verify verification_key.json public.json proof.json
echo Done...